### ISSUE TITLE
ntorrent 

### ISSUE THREAD

**Issue by 123aya123** [spirosmastorakis/nTorrent#3]
Hi
how to know when the peer finish downloading the file  iam using l3tracers
thanks in advance

**Comment by spirosmastorakis** [comment]
Hi, are you running the simulation code in ndnSIM?

**Comment by 123aya123** [comment]
yes, iam working on those simulation scenarios
https://github.com/AkshayRaman/scenario-ntorrent

**Comment by spirosmastorakis** [comment]
You can implement a simple vector of outstanding torrent data packets. Every time a peer downloads a data packet, you will erase it from the vector. Once a peer has downloaded the entire torrent, this vector should be empty. At that time you can use Simulator::Now() to get the current simulation time.

Probably @AkshayRaman could help you implement that if he has time.

**Comment by 123aya123** [comment]
Hi,
sorry to disturb you again
first question
did you provide the implementation for Precise announcements and Approximate announcements   in your ntorrent repo if so, where are they exactly?
second question 
about your simulation result i don't understand what do you mean with data retrieval time in one link (fig.7)?
i really appreciate your help 
@AkshayRaman closed issues on his ntorrent-scenario repo i couldn't reach him

**Comment by spirosmastorakis** [comment]
I either configured FIB manually or used the global routing helper.
Also, x-axis of Figure 7 refers to the simulation time.
