### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by 123aya123** [spirosmastorakis/nTorrent#4]
Hi
i gut the following error while trying to run aproject using ./waf
it  cannot link torrent file or io-util despite they compiled i have searched internet alot but no result it seems to be alinking problem ,it works on eclipse ide
[23/31] Compiling ntorrent/src/torrent-file.cpp
[24/31] Compiling ntorrent/src/util/io-util.cpp
[25/31] Linking build/libntorrent.a
[26/31] Linking build/ntorrent-forwarding-scenario
[27/31] Linking build/ntorrent-fully-connected-consumer
[28/31] Linking build/ntorrent-multi-consumer
extensions/ntorrent-consumer-app.cpp.5.o: In function `ns3::ndn::NTorrentConsumerApp::copyTorrentFile()':
/home/aya/ndnSIM-netcod/scenario-ntorrent/build/../extensions/ntorrent-consumer-app.cpp:196: undefined reference to `ndn::ntorrent::TorrentFile::generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, bool)'
extensions/ntorrent-consumer-app.cpp.5.o: In function `ns3::ndn::NTorrentConsumerApp::OnData(std::shared_ptr<ndn::Data const>)':
/home/aya/ndnSIM-netcod/scenario-ntorrent/build/../extensions/ntorrent-consumer-app.cpp:213: undefined reference to `ndn::ntorrent::IoUtil::findType(ndn::Name const&)'
/home/aya/ndnSIM-netcod/scenario-ntorrent/build/../extensions/ntorrent-consumer-app.cpp:239: undefined reference to `ndn::ntorrent::TorrentFile::TorrentFile(ndn::Block const&)'
/home/aya/ndnSIM-netcod/scenario-ntorrent/build/../extensions/ntorrent-consumer-app.cpp:243: undefined reference to `ndn::ntorrent::TorrentFile::getTorrentFilePtr() const'
extensions/ntorrent-consumer-app.cpp.5.o: In function `ns3::ndn::NTorrentConsumerApp::OnInterest(std::shared_ptr<ndn::Interest const>)':
/home/aya/ndnSIM-netcod/scenario-ntorrent/build/../extensions/ntorrent-consumer-app.cpp:114: undefined reference to `ndn::ntorrent::IoUtil::findType(ndn::Name const&)'
thanks in advance

**Comment by spirosmastorakis** [comment]
You have installed multiple versions of ndnSIM or some of the dependencies (e.g., ndn-cxx, boost) on your system.

You need to use the right version of ndnSIM when compiling the template.

**Comment by 123aya123** [comment]
thanks for your replay
would you explain in steps how can i get rid of this error ?
note that it is running on the original version (akshay simulation)  and i gut that error when i try to run my modified version
thanks

**Comment by spirosmastorakis** [comment]
For that, you need to check your system and see what ns-3 and ndnSIM files are there. I do not know where exactly you have installed NS-3 and ndnSIM. The files might be under the /usr/local/lib directory. Make sure that when you build the template the right version of the simulator is there.

Another reason this might be happening, which is trivial to resolve, is if you have forgotten to include the proper header files in the modified code.

**Comment by 123aya123** [comment]
HI
after i have solved a lot of errors , i get this one and i couldn't solve it after a lot of search 
here is the error i hope you can help 
this happens after i send a directory path "/home/user/somedata" to the generate function in torrent file 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: No such file or directory: iostream error

**Comment by spirosmastorakis** [comment]
Hi,

When you say that you got a lot of errors, you have made custom changes to the original code?

For the simulated version of nTorrent, we specifically used "dummy" data instead of parsing a "real" file.

Please provide more context, so that someone can effectively help you (right now I do not understand what you have done and what exactly is wrong).

Thanks

**Comment by 123aya123** [comment]
Thanks for your reply
sorry for the misunderstand
i didn't mean with errors in your original version i meant my custom version your version is working fine 
i want to simulate with real files and when i provide the path as string for my real file it gives me the past error and i don't know why or where did it come from ? any notes about this error will be helpful
At all , i really appreciate your help

**Comment by spirosmastorakis** [comment]
Why simulating real files is so important? Nothing will change in terms of results.

We have not tried to simulate real file so far, because, as I said, it does not make much sense. There will be no difference in terms of results.

This error says that the file cannot you are looking for be found under the specified directory.
